@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

enum Card << enumeration >> {
  + Card(): 
  + Gatto: 
  + Cornice: 
  + Trofeo: 
  + Empty: 
  + Pianta: 
  + Libro: 
  + Gioco: 
  + valueOf(String): Card
  + values(): Card[]
}
class CardsDeck {
  + CardsDeck(): 
  - cards: Stack<Card>
  + draw(): Optional<Card>
  + size(): int
}
class CommonObjective {
  + CommonObjective(String, int, Function<Shelf, Boolean>): 
  ~ pointDecrement: int
  ~ checkCompleted: Function<Shelf, Boolean>
  ~ name: String
  ~ value: int
  + isCompleted(Shelf): Optional<Trophy>
}
class Game {
  + Game(): 
  - tabletop: TableTop
  - players: ArrayList<Player>
  - commonObjectives: CommonObjective[]
  + getTabletop(): TableTop
  + getCommonObjectives(): CommonObjective[]
  + getPlayers(): ArrayList<Player>
}
class InvalidMoveException {
  + InvalidMoveException(String): 
}
class Objective {
  # Objective(String): 
  - name: String
  + isCompleted(Shelf): Optional<Trophy>
  + equals(Object): boolean
  + getName(): String
}
class PersonalObjective {
  + PersonalObjective(String, Cell[]): 
  - cellsCheck: Cell[]
  + isCompleted(Shelf): Optional<Trophy>
}
class Player {
  + Player(String, PersonalObjective): 
  - trophies: ArrayList<Trophy>
  - name: String
  - personalObjective: PersonalObjective
  - shelf: Shelf
  + getTrophies(): ArrayList<Trophy>
  + getName(): String
  + getPersonalObjective(): PersonalObjective
  + getShelf(): Shelf
}
class Shelf {
  + Shelf(): 
  - ROWS: int
  - slots: Card[][]
  - COLUMNS: int
  + insert(int, Card[]): void
  - getHighest(int): int
}
class TableTop {
  + TableTop(int): 
  ~ nPlayers: int
  - SIZE: int
  - deck: CardsDeck
  - table: Card[][]
  - requiredPlayers: int[][]
  - needRefill(): boolean
  + getDeck(): CardsDeck
  - fillTable(): void
}
class Trophy {
  + Trophy(String, int): 
  - name: String
  - points: int
  + getPoints(): int
  + getName(): String
}

CommonObjective       -[#000082,plain]-^  Objective            
CommonObjective       -[#595959,dashed]->  Trophy               : "«create»"
Game                 "1" *-[#595959,plain]-> "commonObjectives\n*" CommonObjective      
Game                 "1" *-[#595959,plain]-> "players\n*" Player               
Game                 "1" *-[#595959,plain]-> "tabletop\n1" TableTop             
PersonalObjective     -[#000082,plain]-^  Objective            
Player               "1" *-[#595959,plain]-> "personalObjective\n1" PersonalObjective    
Player               "1" *-[#595959,plain]-> "shelf\n1" Shelf                
Player               "1" *-[#595959,plain]-> "trophies\n*" Trophy               
Shelf                "1" *-[#595959,plain]-> "slots\n*" Card                 
Shelf                 -[#595959,dashed]->  Card                 : "«create»"
Shelf                 -[#595959,dashed]->  InvalidMoveException : "«create»"
TableTop              -[#595959,dashed]->  Card                 : "«create»"
TableTop             "1" *-[#595959,plain]-> "table\n*" Card                 
TableTop             "1" *-[#595959,plain]-> "deck\n1" CardsDeck            
@enduml
