@startuml
!theme plain
participant "Client" as C
participant "Server" as S

== Registration ==

note over C, S: Client registers to server using the login process

== Lobby search ==

C -> S: Call Lobbies list service
S -> C: Return list of lobbies
note over C: Chooses lobby to join
C -> S: Call join lobby service
note over S: Verify if lobby is available
S -> C: Return result of join lobby service
note over C: Wait for other players to join

@enduml